# Generated by Django 5.2.8 on 2025-11-16 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('business_license', models.CharField(blank=True, max_length=100, verbose_name='营业执照号码')),
                ('company_address', models.TextField(blank=True, verbose_name='公司地址')),
                ('company_phone', models.CharField(blank=True, max_length=20, verbose_name='公司电话')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='公司邮箱')),
                ('description', models.TextField(blank=True, verbose_name='公司描述')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否审核通过')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='审核日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '商家资料',
                'verbose_name_plural': '商家资料',
            },
        ),
    ]
