# Generated by Django 5.2.8 on 2025-11-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='城市代码')),
                ('name', models.CharField(max_length=50, verbose_name='城市名称')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='省份代码')),
                ('name', models.CharField(max_length=50, verbose_name='省份名称')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='详细地址'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='business_hours',
            field=models.CharField(blank=True, default='09:00-18:00', max_length=50, verbose_name='营业时间'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='business_status',
            field=models.CharField(choices=[('open', '营业中'), ('closed', '休息中'), ('vacation', '休假中')], default='open', max_length=20, verbose_name='营业状态'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='城市代码'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='联系人姓名'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='district',
            field=models.CharField(blank=True, max_length=20, verbose_name='区县代码'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='邮政编码'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='province',
            field=models.CharField(blank=True, max_length=20, verbose_name='省份代码'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='rest_days',
            field=models.CharField(blank=True, default='周六,周日', max_length=100, verbose_name='休息日'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='shipping_methods',
            field=models.JSONField(blank=True, default=list, verbose_name='支持配送方式'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='shipping_time',
            field=models.IntegerField(blank=True, default=2, verbose_name='发货时间(天)'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='store_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='店铺简介'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_logos/', verbose_name='店铺Logo'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='店铺名称'),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='区县代码')),
                ('name', models.CharField(max_length=50, verbose_name='区县名称')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.city', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '区县',
                'verbose_name_plural': '区县',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.province', verbose_name='所属省份'),
        ),
    ]
