# Generated by Django 5.2.8 on 2025-11-16 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='跨境电商平台', max_length=100, verbose_name='站点名称')),
                ('site_description', models.TextField(blank=True, verbose_name='站点描述')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='system/', verbose_name='站点Logo')),
                ('default_currency', models.CharField(default='USD', max_length=3, verbose_name='默认货币')),
                ('payment_gateway_fee', models.DecimalField(decimal_places=2, default=0.03, max_digits=5, verbose_name='支付网关费率')),
                ('merchant_commission_rate', models.DecimalField(decimal_places=2, default=0.05, max_digits=5, verbose_name='商家佣金费率')),
                ('referral_commission_rate', models.DecimalField(decimal_places=2, default=0.01, max_digits=5, verbose_name='推荐佣金费率')),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='默认运费')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='免运费门槛')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='维护模式')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='允许注册')),
                ('require_email_verification', models.BooleanField(default=True, verbose_name='需要邮箱验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
        migrations.CreateModel(
            name='CategoryManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('approve', '审核通过'), ('reject', '审核拒绝')], max_length=20, verbose_name='操作类型')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '分类管理日志',
                'verbose_name_plural': '分类管理日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('promotion_type', models.CharField(choices=[('discount', '折扣'), ('coupon', '优惠券'), ('flash_sale', '闪购'), ('bundle', '套餐')], max_length=20, verbose_name='促销类型')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='折扣百分比')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='折扣金额')),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最低订单金额')),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最大折扣金额')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('paused', '暂停'), ('ended', '已结束')], default='draft', max_length=20, verbose_name='状态')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='使用限制')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicable_categories', models.ManyToManyField(blank=True, to='products.category', verbose_name='适用分类')),
                ('applicable_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='适用商品')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '促销活动',
                'verbose_name_plural': '促销活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], max_length=20, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('module', models.CharField(max_length=100, verbose_name='模块')),
                ('function', models.CharField(max_length=100, verbose_name='函数')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
