# Generated by Django 5.2.8 on 2025-11-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='已评价'),
        ),
        migrations.AddField(
            model_name='order',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='评价内容'),
        ),
        migrations.AddField(
            model_name='order',
            name='review_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='评价评分'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_comment',
            field=models.TextField(blank=True, verbose_name='服务评价'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='服务评分'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='商品评分'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='商品评价'),
        ),
    ]
